spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.entity
server:
  port: 80
  servlet:
    context-path: "/"